import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import AppRoutes from './routes';
import { AuthProvider } from './contexts/AuthContext';
import { AdminAuthProvider } from './contexts/AdminAuthContext';
import { BalanceVisibilityProvider } from './contexts/BalanceVisibilityContext';
import { ToastProvider } from './contexts/ToastContext';
import ToastContainer from './components/Toast';
import './styles/tailwind.css';
const queryClient = new QueryClient();
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(QueryClientProvider, { client: queryClient, children: _jsx(BrowserRouter, { children: _jsx(ToastProvider, { children: _jsx(AuthProvider, { children: _jsx(AdminAuthProvider, { children: _jsxs(BalanceVisibilityProvider, { children: [_jsx(AppRoutes, {}), _jsx(ToastContainer, {})] }) }) }) }) }) }) }));
